# Generated by Django 6.0.1 on 2026-01-08 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_address_zip'),
    ]

    operations = [
    ]
